### ISSUE TITLE
Pink lines appearing in images on Android Chrome browser when "AVIF conversion" is enabled in Optimole settings.

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#504] opened 2023-03-27 14:56 UTC
### Description

A user reported that - 

When the "AVIF conversion" option is enabled in Optimole settings, images on the Android Chrome browser are appearing with pink lines. However, the problem disappears when the option is disabled. 

He has confirmed that creating an exception in Optimole to not optimize the affected image resolves the issue. This problem seems to be specific to the mobile Android Chrome browsers, across various versions. 

However, I couldn't replicate the same behavior on my test instance but on his site, I can see that pink images appears with Optimole AVIF, and later on I found that a similar behavior appears on the CodeinWP site too(check references)

### Step-by-step reproduction instructions

- Enable the "AVIF conversion" option in Optimole settings.
- Visit the website on the mobile Android Chrome browser.
- Observe the images for pink lines.

### Screenshots, screen recording, code snippet or Help Scout ticket

![image](https://user-images.githubusercontent.com/110405452/227977459-cfdcfac4-686e-4e37-a1b4-c3655d3acac6.png)
![image](https://user-images.githubusercontent.com/110405452/227977624-cbcc425e-df2b-4c75-ad0f-c4ae10583f56.png)

See the P in codeinwp:
![image](https://user-images.githubusercontent.com/110405452/227977724-f30589a2-a276-4854-821c-8a57f9b43947.png)

HS ticket: https://secure.helpscout.net/conversation/2192462357/362939?folderId=2353196
The user site where this behavior is present: https://dev.incentea-mi.pt/core/dynamics-365-business-central/
CodeinWP page : https://www.codeinwp.com/wordpress-contest/

### Is the issue you are reporting a regression

No

**Comment by kushh23** [comment] 2023-04-11 12:21
https://demo-ppom-lite.vertisite.cloud/?utm_source=themeisle&utm_medium=product&utm_campaign=front

![Screenshot_2023-04-11-17-51-12-766_com.android.chrome.jpg](https://user-images.githubusercontent.com/110405452/231160776-4ce85893-87c3-496a-9a3f-2d5a7df16d12.jpg)

**Comment by kushh23** [comment] 2023-04-12 12:26
+1: https://secure.helpscout.net/conversation/2211169759/365549?folderId=2353196

**Comment by selul** [comment] 2023-04-15 14:53
@kushh23 I'm not able to replicate this on BrowserStack, which is testing using a real device. 

I was wondering if you could share the image link, the one with pink, by right-clicking on it and copying the Image URL. 

This should help me isolate the issue.

Thanks!

**Comment by kushh23** [comment] 2023-04-15 15:01
Here it is @selul 

https://mlwes2arpcu4.i.optimole.com/cb:JElQ.3f382/w:167/h:167/q:mauto/dpr:2.8/rt:fill/g:ce/f:avif/https://demo-ppom-lite.vertisite.cloud/wp-content/uploads/2023/02/9.png

**Comment by kushh23** [comment] 2023-04-15 15:03
This issue seems to appear only on the mobile phone, https://vertis.d.pr/i/mpWcR3

**Comment by HardeepAsrani** [comment] 2023-04-17 07:42
@selul Few weeks back, I was able to reproduce this on a friend's Android phone, and I had done some search on this and found other instances of it being reported on other places: https://github.com/php/php-src/issues/8154#issuecomment-1455272753 https://irfanview-forum.de/forum/program/bugreports/96336-bug-weird-purple-line-when-open-avif

**Comment by kushh23** [comment] 2023-04-27 15:27
+1: https://secure.helpscout.net/conversation/2211169759/365549?folderId=2353196

**Comment by HardeepAsrani** [comment] 2023-05-05 06:46
https://bugs.chromium.org/p/chromium/issues/detail?id=1429594

**Comment by kushh23** [comment] 2023-05-22 13:42
@selul yes, I am able to replicate this behavior even now.

**Comment by selul** [comment] 2023-05-22 15:39
interesting, can you do the following as it might be due to cache:  open the link where this is happening and change the `w:` in the URL to some other number.

**Comment by kushh23** [comment] 2023-05-23 12:16
Yes, it disappears after changing the width parameter.

**Comment by abaicus** [comment] 2023-06-30 14:42
Thank you for the update, @kushh23! I checked, and things work well. I will close this for now, but please feel free to open it back up if you encounter the issue! 

Thanks! 👍🏻

**Closed by abaicus** 2023-06-30 14:42 UTC
Labels: bug, customer report
