### ISSUE TITLE
bug: Some special characters break the URL

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/optimole-wp#374] opened 2021-06-07 21:14 UTC
**Describe the bug**
Similar to how some special language characters were not being processed correctly.
Reported here:
https://secure.helpscout.net/conversation/1526898068/280368/

I've tested it in a test instance and the same issue occurred, when image is renamed it's served properly:
![image](https://user-images.githubusercontent.com/36594177/121088462-78eeec80-c7ee-11eb-996a-42a981e80fda.png)

**To Reproduce**
1. Add an image that contains inside the file path a special char like -—-
Example name - Sunny-16-—-Premium-Camera-Backpacks-—-Early-Sketches-1024x683-1.jpg
2. The image will break

**Expected behavior**
The image should load.

A similar issue was reported and fixed here - https://github.com/Codeinwp/optimole-wp/issues/326

**Comment by GrigoreMihai** [comment] 2021-08-13 17:21
This looks like it was fixed here https://github.com/Codeinwp/optimole-wp/commit/f11378791d62d3501951bb4462e781ba3faf4c90 . From my testing it is working .

**Comment by gutoslv** [comment] 2021-08-18 01:01
The issue is fixed with the mentioned commit.

**Closed** 2021-08-18 12:35 UTC
Labels: bug
