### ISSUE TITLE
View Sample Image doesn't show anything

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#515] opened 2023-04-07 08:58 UTC
### Description

When I click on the View Sample Image, it just loads, but doesn't show anything.

Also, if I disable the Auto Quality option and modify the quality level, then decide to turn Auto Quality back again, the View sample image still appears ( it doesn't appear by default ). Is this the desired behavior?

### Step-by-step reproduction instructions

1. Go to Media > Optimole
2. Open Settings > Advanced > Compression
3. Disable the Auto Quality toggle
4. Try to change the quality 
5. Click on the View sample image option

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/86592992/230577325-f43566d9-0db0-43ec-be12-d2d3ef749129.png">

### Is the issue you are reporting a regression

I am not sure if this is a regression.

**Comment by selul** [comment] 2023-04-07 08:59
@AndreeaCristinaRadacina why this is marked as a regression, was working fine in the previous version?

**Comment by AndreeaCristinaRadacina** [comment] 2023-04-07 09:00
Sorry, I was editing the issue when you posted this.
I am not sure if it is a regression.

**Comment by AndreeaCristinaRadacina** [comment] 2023-04-07 09:03
It doesn't work in 3.5.7 either.

**Comment by kushh23** [comment] 2023-04-07 11:36
Hey, I tried replicating this issue on my instances, and on all three of them, the issue doesn't appear to me as shown here - https://vertis.d.pr/v/hthuZX

The sample image loads fine on my end.

> Also, if I disable the Auto Quality option and modify the quality level, then decide to turn Auto Quality back again, the View sample image still appears ( it doesn't appear by default ). Is this the desired behavior?

This seems to happen on my instance as well but after doing a refresh it disappears, not sure if it is a bug or its desired behavior. https://vertis.d.pr/v/e4bFFx

I suspected that it could be related to the cache but even after clearing the cache and reinstalling the plugin the issue still appears on her instance.

**Comment by HardeepAsrani** [comment] 2023-04-24 23:15
I fixed the issue Kush found, for the first issue it seems I could only reproduce it on local instance where we weren't able to detect image sizes.

@AndreeaCristinaRadacina were you testing that locally or online?

**Comment by AndreeaCristinaRadacina** [comment] 2023-04-25 12:00
I was testing locally, indeed.

**Comment by HardeepAsrani** [comment] 2023-04-25 18:33
That's what I expected; I ran some tests, and that behavior seems to be due to you using a local instance, where Optimole isn't able to send images to its server to try and show you the optimized version.

For the issues that Kush has found, I've created https://github.com/Codeinwp/optimole-wp/pull/528

Let me know if anything else needs to be done here.

**Closed** 2023-05-15 13:09 UTC
Labels: bug, tiny
